# Generated by Django 4.1.5 on 2023-01-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='photo',
            field=models.ImageField(help_text='Скинь фотку', upload_to=''),
        ),
    ]
