# Generated by Django 4.1.5 on 2023-01-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_content_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, help_text='Скинь фотку', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='content',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.category'),
        ),
    ]
