# Generated by Django 4.1.5 on 2023-01-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0009_alter_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
